const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    background: '#0a0c12',
    overflow: 'hidden',
    height: '100%',
    minHeight: 0,
    width: '100%',
  },
  empty: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#4a5070',
    fontSize: '15px',
  },
  header: {
    padding: '18px 24px',
    borderBottom: '1px solid #1e2130',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    flexShrink: 0,
  },
  squadIcon: {
    position: 'relative',
    width: '52px',
    height: '52px',
    borderRadius: '14px',
    background: '#1e2a4a',
    border: '1px solid #2a3a6a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '22px',
    flexShrink: 0,
  },
  onlineDot: {
    position: 'absolute',
    bottom: '2px',
    right: '2px',
    width: '11px',
    height: '11px',
    borderRadius: '50%',
    background: '#10b981',
    border: '2px solid #0f1117',
  },
  squadInfo: { flex: 1, minWidth: 0 },
  squadName: {
    fontSize: '18px',
    fontWeight: '800',
    color: '#f0f4ff',
    lineHeight: 1.25,
  },
  squadMeta: {
    fontSize: '13px',
    color: '#94a3b8',
    marginTop: '2px',
  },
  actions: {
    display: 'flex',
    gap: '10px',
    flexShrink: 0,
  },
  inviteBtn: {
    background: '#1e2130',
    color: '#c0c8e8',
    border: '1px solid #2a3050',
    padding: '9px 16px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  leaveBtn: {
    background: '#1e2130',
    color: '#ef4444',
    border: '1px solid #2a3050',
    padding: '9px 16px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  iconBtn: {
    background: '#1e2130',
    color: '#c0c8e8',
    border: '1px solid #2a3050',
    padding: '9px 12px',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  tabs: {
    display: 'flex',
    flexWrap: 'nowrap',
    overflowX: 'auto',
    borderBottom: '1px solid #1e2130',
    padding: '0 20px',
    flexShrink: 0,
    scrollbarWidth: 'none',
  },
  tab: (active, accentColor) => ({
    padding: '14px 18px',
    border: 'none',
    background: active ? `${accentColor}1f` : 'transparent',
    color: active ? '#e2e8f0' : '#94a3b8',
    fontSize: '14px',
    fontWeight: active ? '700' : '500',
    cursor: 'pointer',
    borderBottom: active ? `2px solid ${accentColor}` : '2px solid transparent',
    marginBottom: '-1px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    transition: '0.2s all ease',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  }),
  tabCount: {
    background: 'rgba(15, 23, 42, 0.9)',
    color: '#60a5fa',
    fontSize: '11px',
    padding: '2px 7px',
    borderRadius: '4px',
    fontWeight: '700',
  },
  pinned: {
    margin: '12px 20px 0',
    padding: '12px 16px',
    background: '#1a1e2e',
    borderRadius: '10px',
    border: '1px solid #2a3050',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '13px',
    flexShrink: 0,
  },
  pinnedBy: { color: '#7a86b6' },
  pinnedName: { color: '#3b82f6', fontWeight: '700' },
  pinnedText: { color: '#c0c8e8', flex: 1, fontSize: '13px' },
  viewBtn: {
    background: '#3b82f6',
    color: '#fff',
    border: 'none',
    padding: '5px 12px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: '700',
    cursor: 'pointer',
  },
  content: {
    flex: 1,
    minHeight: 0,
    color: '#c0c8e8',
    fontSize: '15px',
    padding: '24px',
    lineHeight: 1.5,
  },
  chatPane: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
};

export default styles;
