"""Demo public job listings for Jobs hub browse (upserted on startup)."""

DEMO_HUB_JOB_ROWS = [
    {
        "_id": "job-demo-frontend-developer",
        "public_slug": "frontend-developer",
        "title": "Frontend Developer",
        "category": "Web Development",
        "summary": "Build responsive web interfaces with modern JavaScript and component libraries.",
        "description": "Join a product team shipping dashboard and marketplace experiences with React and accessible UI patterns.",
        "salary_range": "$85K - $115K",
        "compensation_band": {"min": 85, "max": 115},
        "remote": True,
        "location": "Remote",
        "employment_type": "Full-time",
        "company_name": "PixelCraft",
        "posted_ago": "3h ago",
        "experience_level": "Mid Level",
        "work_mode": "Remote",
        "skills_tags": ["HTML", "CSS", "JavaScript", "React"],
        "visibility": "public",
        "showroom_seed": True,
        "status": "active",
        "is_approved": True,
    },
    {
        "_id": "job-demo-react-developer",
        "public_slug": "react-developer",
        "title": "React Developer",
        "category": "Web Development",
        "summary": "Own feature delivery in a React codebase with strong TypeScript practices.",
        "description": "Implement reusable components, state management, and performance improvements across customer-facing apps.",
        "salary_range": "$95K - $130K",
        "compensation_band": {"min": 95, "max": 130},
        "remote": True,
        "location": "Remote",
        "employment_type": "Full-time",
        "company_name": "StackBridge",
        "posted_ago": "5h ago",
        "experience_level": "Mid Level",
        "work_mode": "Remote",
        "skills_tags": ["React", "TypeScript", "Redux", "Jest"],
        "visibility": "public",
        "showroom_seed": True,
        "status": "open",
    },
    {
        "_id": "job-demo-seo-specialist",
        "public_slug": "seo-specialist",
        "title": "SEO Specialist",
        "category": "SEO & Marketing",
        "summary": "Grow organic traffic with technical SEO, content strategy, and analytics.",
        "description": "Audit sites, fix crawl issues, and partner with content teams on keyword-led campaigns.",
        "salary_range": "$55K - $80K",
        "compensation_band": {"min": 55, "max": 80},
        "remote": True,
        "location": "Hybrid · Austin, USA",
        "employment_type": "Full-time",
        "company_name": "RankFlow",
        "posted_ago": "1d ago",
        "experience_level": "Mid Level",
        "work_mode": "Hybrid",
        "skills_tags": ["SEO", "Google Analytics", "Ahrefs", "Content Strategy"],
        "visibility": "public",
        "showroom_seed": True,
        "status": "open",
    },
    {
        "_id": "job-demo-content-writer",
        "public_slug": "content-writer",
        "title": "Content Writer",
        "category": "Writing & Translation",
        "summary": "Create clear, engaging copy for blogs, landing pages, and product marketing.",
        "description": "Research topics, draft SEO-friendly articles, and refine tone for global audiences.",
        "salary_range": "$45K - $65K",
        "compensation_band": {"min": 45, "max": 65},
        "remote": True,
        "location": "Remote",
        "employment_type": "Contract",
        "company_name": "Storyline Media",
        "posted_ago": "6h ago",
        "experience_level": "Entry Level",
        "work_mode": "Remote",
        "skills_tags": ["Copywriting", "Blogging", "SEO Writing", "Editing"],
        "visibility": "public",
        "showroom_seed": True,
        "status": "open",
    },
    {
        "_id": "job-demo-graphic-designer",
        "public_slug": "graphic-designer",
        "title": "Graphic Designer",
        "category": "Design & Creative",
        "summary": "Design brand assets, social creatives, and marketing visuals.",
        "description": "Deliver polished layouts in Figma and Adobe tools for campaigns and product launches.",
        "salary_range": "$50K - $75K",
        "compensation_band": {"min": 50, "max": 75},
        "remote": False,
        "location": "On-site · Toronto, Canada",
        "employment_type": "Full-time",
        "company_name": "ColorMint Studio",
        "posted_ago": "2d ago",
        "experience_level": "Mid Level",
        "work_mode": "On-site",
        "skills_tags": ["Photoshop", "Illustrator", "Figma", "Branding"],
        "visibility": "public",
        "showroom_seed": True,
        "status": "open",
    },
    {
        "_id": "job-demo-ai-engineer",
        "public_slug": "ai-engineer",
        "title": "AI Engineer",
        "category": "Development",
        "summary": "Build and deploy ML features, LLM integrations, and data pipelines.",
        "description": "Prototype models, productionize APIs, and collaborate on responsible AI guardrails.",
        "salary_range": "$140K - $190K",
        "compensation_band": {"min": 140, "max": 190},
        "remote": True,
        "location": "Remote",
        "employment_type": "Full-time",
        "company_name": "NeuralForge",
        "posted_ago": "4h ago",
        "experience_level": "Senior Level",
        "work_mode": "Remote",
        "skills_tags": ["Python", "PyTorch", "LLMs", "MLOps"],
        "visibility": "public",
        "showroom_seed": True,
        "status": "open",
    },
    {
        "_id": "job-demo-mobile-app-developer",
        "public_slug": "mobile-app-developer",
        "title": "Mobile App Developer",
        "category": "Mobile Development",
        "summary": "Ship cross-platform mobile apps with React Native and native integrations.",
        "description": "Own app releases, push notifications, and App Store / Play Store delivery workflows.",
        "salary_range": "$100K - $140K",
        "compensation_band": {"min": 100, "max": 140},
        "remote": True,
        "location": "Hybrid · Berlin, Germany",
        "employment_type": "Full-time",
        "company_name": "AppOrbit",
        "posted_ago": "8h ago",
        "experience_level": "Mid Level",
        "work_mode": "Hybrid",
        "skills_tags": ["React Native", "iOS", "Android", "Firebase"],
        "visibility": "public",
        "showroom_seed": True,
        "status": "open",
    },
    {
        "_id": "job-demo-wordpress-expert",
        "public_slug": "wordpress-expert",
        "title": "WordPress Expert",
        "category": "Web Development",
        "summary": "Customize WordPress themes, plugins, and WooCommerce storefronts.",
        "description": "Maintain high-performance sites, security updates, and client-ready CMS workflows.",
        "salary_range": "$60K - $90K",
        "compensation_band": {"min": 60, "max": 90},
        "remote": True,
        "location": "Remote",
        "employment_type": "Part-time",
        "company_name": "SiteMakers",
        "posted_ago": "12h ago",
        "experience_level": "Mid Level",
        "work_mode": "Remote",
        "skills_tags": ["WordPress", "PHP", "WooCommerce", "Elementor"],
        "visibility": "public",
        "showroom_seed": True,
        "status": "open",
    },
]
