"""Locked E-1 .. E-6 elite matrix seed — synced with renk sistam.png."""
from __future__ import annotations

from typing import Any

RANK_BADGE_BASE = "/static/uploads/ranks"

ELITE_DEFAULT_RANKS: list[dict[str, Any]] = [
    {
        "rank_id": "e-1",
        "rankCode": "E-1",
        "rankName": "Frontline Recruit",
        "name": "Frontline Recruit",
        "minPoints": 0,
        "minDealsRequired": 0,
        "minStarRating": 0.0,
        "iconUrl": f"{RANK_BADGE_BASE}/e-1-emerald-dual-star-crest.png",
        "icon": "🪖",
        "featureOnFrontlineDashboard": False,
        "benefits": "Basic profile visibility. Standard bidding limit on gigs.",
        "matrixVersion": 2,
        "status": "active",
        "users": 0,
        "createdOn": "2026-01-01",
        "updatedOn": "2026-01-01",
    },
    {
        "rank_id": "e-2",
        "rankCode": "E-2",
        "rankName": "Frontline Specialist",
        "name": "Frontline Specialist",
        "minPoints": 1000,
        "minDealsRequired": 3,
        "minStarRating": 4.2,
        "iconUrl": f"{RANK_BADGE_BASE}/e-2-cyan-tri-chevron-shield.png",
        "icon": "⚔️",
        "featureOnFrontlineDashboard": False,
        "benefits": "Specialist badge on profile. Squad join permission unlocked.",
        "matrixVersion": 2,
        "status": "active",
        "users": 0,
        "createdOn": "2026-01-01",
        "updatedOn": "2026-01-01",
    },
    {
        "rank_id": "e-3",
        "rankCode": "E-3",
        "rankName": "Tactical Operative",
        "name": "Tactical Operative",
        "minPoints": 3500,
        "minDealsRequired": 10,
        "minStarRating": 4.5,
        "iconUrl": f"{RANK_BADGE_BASE}/e-3-platinum-winged-shield.png",
        "icon": "🎯",
        "featureOnFrontlineDashboard": False,
        "benefits": "Silver highlight on proposals. 2% platform fee discount.",
        "matrixVersion": 2,
        "status": "active",
        "users": 0,
        "createdOn": "2026-01-01",
        "updatedOn": "2026-01-01",
    },
    {
        "rank_id": "e-4",
        "rankCode": "E-4",
        "rankName": "Squad Commander",
        "name": "Squad Commander",
        "minPoints": 7000,
        "minDealsRequired": 25,
        "minStarRating": 4.7,
        "iconUrl": f"{RANK_BADGE_BASE}/e-4-golden-tri-star-crest.png",
        "icon": "🛡️",
        "featureOnFrontlineDashboard": False,
        "benefits": "Priority above normal users in bidding. Create squad/team permission.",
        "matrixVersion": 2,
        "status": "active",
        "users": 0,
        "createdOn": "2026-01-01",
        "updatedOn": "2026-01-01",
    },
    {
        "rank_id": "e-5",
        "rankCode": "E-5",
        "rankName": "Elite Commander",
        "name": "Elite Commander",
        "minPoints": 15000,
        "minDealsRequired": 50,
        "minStarRating": 4.8,
        "iconUrl": f"{RANK_BADGE_BASE}/e-5-crimson-ruby-wreath-crown.png",
        "icon": "🔱",
        "featureOnFrontlineDashboard": False,
        "benefits": "VIP badge. 1-hour early exclusive access to new gigs.",
        "matrixVersion": 2,
        "status": "active",
        "users": 0,
        "createdOn": "2026-01-01",
        "updatedOn": "2026-01-01",
    },
    {
        "rank_id": "e-6",
        "rankCode": "E-6",
        "rankName": "Apex Vanguard",
        "name": "Apex Vanguard",
        "minPoints": 30000,
        "minDealsRequired": 100,
        "minStarRating": 4.9,
        "iconUrl": f"{RANK_BADGE_BASE}/e-6-gold-crown-onyx-core.png",
        "icon": "👑",
        "featureOnFrontlineDashboard": True,
        "benefits": "Frontline featured atop recruiter dashboards. Official elite verified token.",
        "matrixVersion": 2,
        "status": "active",
        "users": 0,
        "createdOn": "2026-01-01",
        "updatedOn": "2026-01-01",
    },
]

LEGACY_RANK_IDS = ("rookie", "skilled", "pro", "elite", "commander")
