export const DEFAULT_JOB_SETTINGS = {
  jobsEnabled: true,
  requireAdminApproval: true,
  companyVerificationRequired: true,
  resumeRequiredToApply: true,
  emailAlertsDefaultOn: true,
  maxAlertsPerUser: 20,
  autoExpireDays: 60,
  showAssessmentSection: false,
  showInterviewSection: false,
  showSalarySection: false,
};

export const JOB_SETTING_ROWS = [
  {
    id: 'jobsEnabled',
    label: 'Jobs Hub Enabled',
    description: 'Show the Jobs hub to members',
    type: 'toggle',
    icon: 'briefcase',
  },
  {
    id: 'requireAdminApproval',
    label: 'Require Admin Approval',
    description: 'Company job posts stay pending until approved',
    type: 'toggle',
    icon: 'shield',
  },
  {
    id: 'companyVerificationRequired',
    label: 'Company Verification Gate',
    description: 'Only verified companies can post permanent jobs',
    type: 'toggle',
    icon: 'building',
  },
  {
    id: 'resumeRequiredToApply',
    label: 'Resume Required',
    description: 'Require a resume when applying with upload flow',
    type: 'toggle',
    icon: 'file',
  },
  {
    id: 'emailAlertsDefaultOn',
    label: 'Email Alerts Default On',
    description: 'New job alerts start with email notifications enabled',
    type: 'toggle',
    icon: 'bell',
  },
  {
    id: 'maxAlertsPerUser',
    label: 'Max Alerts Per User',
    description: 'Maximum saved job alerts a seeker can create',
    type: 'number',
    icon: 'hash',
  },
  {
    id: 'autoExpireDays',
    label: 'Auto-Expire Days',
    description: 'Days before an approved listing can expire',
    type: 'number',
    icon: 'calendar',
  },
  {
    id: 'showAssessmentSection',
    label: 'Skill Assessment',
    description: 'Show Skill Assessment in the Jobs sidebar',
    type: 'toggle',
    icon: 'award',
  },
  {
    id: 'showInterviewSection',
    label: 'Interview Prep',
    description: 'Show Job Interview Prep in the Jobs sidebar',
    type: 'toggle',
    icon: 'target',
  },
  {
    id: 'showSalarySection',
    label: 'Salary Insights',
    description: 'Show Salary Insights in the Jobs sidebar',
    type: 'toggle',
    icon: 'layers',
  },
];
