import {
  FiBriefcase,
  FiBookOpen,
  FiCloud,
  FiCode,
  FiCpu,
  FiDatabase,
  FiDollarSign,
  FiEdit3,
  FiFileText,
  FiGlobe,
  FiGrid,
  FiHeadphones,
  FiLayers,
  FiMusic,
  FiShield,
  FiShare2,
  FiSmartphone,
  FiTarget,
  FiTrendingUp,
  FiUser,
  FiVideo,
} from 'react-icons/fi';

/** Icons for global service category `iconKey` (see `data/globalCategories`). */
export const gigsCategoryIcons = {
  code: FiCode,
  cpu: FiCpu,
  trending: FiTrendingUp,
  pen: FiEdit3,
  edit: FiEdit3,
  video: FiVideo,
  smartphone: FiSmartphone,
  briefcase: FiBriefcase,
  shopping: FiBriefcase,
  share: FiShare2,
  database: FiDatabase,
  shield: FiShield,
  cloud: FiCloud,
  layers: FiLayers,
  target: FiTarget,
  headphones: FiHeadphones,
  dollar: FiDollarSign,
  file: FiFileText,
  grid: FiGrid,
  globe: FiGlobe,
  music: FiMusic,
  user: FiUser,
  book: FiBookOpen,
  gamepad: FiGrid,
};

export { FiGrid as GigsCategoryIconFallback };
