const styles = {
  container: { display: 'flex', flexDirection: 'column', gap: '15px' },
  inputRow: { display: 'flex', gap: '10px', alignItems: 'center', marginBottom: '10px' },
  avatar: { width: '32px', height: '32px', borderRadius: '50%', background: '#3b82f6', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: '12px', fontWeight: 'bold' },
  inputBox: { flex: 1, display: 'flex', background: '#1b222b', border: '1px solid #334155', borderRadius: '20px', padding: '6px 12px' },
  input: { flex: 1, background: 'none', border: 'none', color: '#e2e8f0', outline: 'none', fontSize: '13px' },
  inputIcons: { display: 'flex', gap: '8px', alignItems: 'center' },
  helperText: { fontSize: '11px', color: '#8b949e', margin: '0 0 4px 44px' },
  selectedPreviewImage: { marginLeft: '44px', marginTop: '4px', width: '120px', height: '90px', objectFit: 'cover', borderRadius: '10px', border: '1px solid #334155' },
  icon: { color: '#8b949e', cursor: 'pointer' },
  iconButton: { background: 'none', border: 'none', padding: 0, cursor: 'pointer', display: 'flex', alignItems: 'center' },
  sendBtn: { background: 'none', border: 'none', cursor: 'pointer' },
  emojiPickerWrap: { marginLeft: '44px', marginTop: '4px' },
  list: { display: 'flex', flexDirection: 'column', gap: '20px' },
  commentBlock: { position: 'relative' },
  commentRow: { display: 'flex', gap: '10px' },
  commentAvatar: { width: '32px', height: '32px', borderRadius: '50%', background: '#30363d', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#3b82f6', fontWeight: 'bold' },
  bubble: { flex: 1, background: '#232a35', borderRadius: '0 12px 12px 12px', padding: '8px 12px' },
  bubbleHeader: { display: 'flex', justifyContent: 'space-between' },
  menuWrap: { position: 'relative' },
  menu: { position: 'absolute', right: 0, top: '110%', minWidth: '120px', background: '#1b222b', border: '1px solid #334155', borderRadius: '8px', zIndex: 20, overflow: 'hidden' },
  menuItem: { width: '100%', background: 'transparent', border: 'none', color: '#e2e8f0', textAlign: 'left', fontSize: '12px', padding: '8px 10px', cursor: 'pointer' },
  commenterName: { fontSize: '13px', fontWeight: 'bold', color: '#fff' },
  dot: { color: '#8b949e', fontWeight: 'normal' },
  commenterTitle: { fontSize: '11px', color: '#8b949e', margin: '2px 0 5px' },
  commentText: { fontSize: '14px', color: '#f1f5f9', margin: 0, lineHeight: 1.5 },
  commentImage: { marginTop: '8px', width: '100%', maxWidth: '280px', borderRadius: '10px', border: '1px solid #334155', objectFit: 'cover' },
  attachmentTag: { margin: '6px 0 0', fontSize: '11px', color: '#60a5fa' },
  commentActions: { display: 'flex', gap: '10px', marginLeft: '42px', marginTop: '4px' },
  actionBtn: { background: 'none', border: 'none', color: '#8b949e', fontSize: '11px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' },
  actionDivider: { color: '#334155' },
  repliesList: { marginLeft: '42px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '6px' },
  replyItem: { fontSize: '12px', color: '#cbd5e1', background: '#1e2530', border: '1px solid #334155', borderRadius: '8px', padding: '6px 10px' },
  replyMetaRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px', marginBottom: '4px' },
  replyAuthor: { color: '#fff', fontWeight: 600 },
  replyText: { color: '#cbd5e1' },
  replyActionBtn: { background: 'none', border: 'none', color: '#60a5fa', fontSize: '11px', cursor: 'pointer', padding: 0 },
  replyComposer: { marginLeft: '42px', marginTop: '8px' },
  replyComposerNested: { marginTop: '8px' }
};

export default styles;
